version: '3'

services:
  proto-golang: 
    image: ghcr.io/tk42/protoc
    volumes: 
      - .:/tmp
    working_dir: "/tmp"
    command: ["protoc", "--go_out=.", "--go-grpc_out=.", "-I.", "./helloworld.proto"]
    # command: ["protoc", "--go_out=.", "--go-grpc_out=.", "--grpc-gateway_out=.", "-I.", "./helloworld.proto"] # TODO: set PATH to google/api

  proto-python: 
    image: ghcr.io/tk42/protoc
    volumes: 
      - .:/tmp
    working_dir: "/tmp"
    # Note: use 'python3 -m grpc_tools.protoc'
    command: ["python3", "-m", "grpc_tools.protoc", "--python_out=./example.com/hello", "--grpc_python_out=./example.com/hello", "-I.", "./helloworld.proto"]
